url: 'https://giovannycordeiro.github.io'
baseurl: 'my_page'
title: ''

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
